// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkxXeHITVWPrzWj1f-ZrUHH199XaJsb0',
    appId: '1:24328478509:web:d7ba1108ee8b113495fda4',
    messagingSenderId: '24328478509',
    projectId: 'quanlypets',
    authDomain: 'quanlypets.firebaseapp.com',
    storageBucket: 'quanlypets.firebasestorage.app',
    measurementId: 'G-KZJHPXX5MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWiVP-o62QYH5ya-s23J70zrSWqQWnMcU',
    appId: '1:24328478509:android:94cab3cf783f3ed195fda4',
    messagingSenderId: '24328478509',
    projectId: 'quanlypets',
    storageBucket: 'quanlypets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9m4FTm0d8oL-xu583KLjNgGTjc3eOUT8',
    appId: '1:24328478509:ios:dce308749c8fc76095fda4',
    messagingSenderId: '24328478509',
    projectId: 'quanlypets',
    storageBucket: 'quanlypets.firebasestorage.app',
    iosBundleId: 'com.example.listproduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9m4FTm0d8oL-xu583KLjNgGTjc3eOUT8',
    appId: '1:24328478509:ios:dce308749c8fc76095fda4',
    messagingSenderId: '24328478509',
    projectId: 'quanlypets',
    storageBucket: 'quanlypets.firebasestorage.app',
    iosBundleId: 'com.example.listproduct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkxXeHITVWPrzWj1f-ZrUHH199XaJsb0',
    appId: '1:24328478509:web:bf0d91dfafd3ea5395fda4',
    messagingSenderId: '24328478509',
    projectId: 'quanlypets',
    authDomain: 'quanlypets.firebaseapp.com',
    storageBucket: 'quanlypets.firebasestorage.app',
    measurementId: 'G-74X7KLWL3L',
  );
}
